param = abmset('ntype',2, ...
               'domx',2000, ...
               'domy',1000, ...
               'domxt',130, ...
               'domyt',130, ...
               'rm',20, ...
               'rx',20, ...
               'gamma_loc', 75, ...
               'gamma_long_inner', 75, ...
               'gamma_long_outer', 75, ...
               'mu', 1, ...
               'nu', 1, ...
               'psi', 1.2, ...
               'p_d', 1./30, ...
               'alpha', 1, ...
               'beta', 3.5, ...
               'eta', 6, ...
               'd_crowd', 82, ...
               'phi_1', 1.3, ...
               'phi_2', 1.2, ...
               'kappa', 10, ...
               'd_rand', 100, ...
               'hmwidth', 100);